auto_sync = false
dialect = "uk"
inline_height = 11
show_help = false
show_preview = false
style = "compact"
update_check = false

history_filter = [
  "^cd ",
  "^cd$",
  "^cdg$",
  "^clean$",
  "^exit$",
  "^l ",
  "^l$",
  "^la ",
  "^la$",
  "^lfcd$",
  "^ll ",
  "^ll$",
  "^lt ",
  "^lt$"
]
