auto_sync = false
dialect = "uk"
inline_height = 11
show_help = false
show_preview = false
style = "compact"
update_check = false

history_filter = [
  "^cd ",
  "^cd$",
  "^cdg$",
  "^clean$",
  "^exit$",
  "^g .*--abort.*",
  "^g .*--continue.*",
  "^g .*--quit.*",
  "^g .*--skip.*",
  "^g a .$",
  "^g c$",
  "^g ca$",
  "^g ce$",
  "^g ch .$",
  "^g d$",
  "^g dd$",
  "^g ds$",
  "^g f$",
  "^g i$",
  "^g l$",
  "^g ll$",
  "^g pl$",
  "^g plf$",
  "^g pop$",
  "^g ps$",
  "^g psf$",
  "^g rank$",
  "^g root$",
  "^g rvh$",
  "^g s$",
  "^g st$",
  "^l ",
  "^l$",
  "^la ",
  "^la$",
  "^lfcd$",
  "^ll ",
  "^ll$",
  "^lt ",
  "^lt$"
]
