"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.prepend_keymap]]
on   = [ "d" ]
run  = "remove --permanently"
desc = "Permanently delete the files"

[[mgr.prepend_keymap]]
on   = [ "D" ]
run  = "remove --force --permanently"
desc = "Permanently delete the files without confirmation"

[[input.prepend_keymap]]
on   = [ "<Esc>" ]
run  = "close"
desc = "Cancel input"
