"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[flavor]
use = "rose-pine"

[manager]
preview_hovered = { fg = "#e0def4", bg = "#26233a" }

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "#9ccfd8" },

  # Videos
  { mime = "video/*", fg = "#f6c177" },
  { mime = "audio/*", fg = "#f6c177" },

  # Archives
  { mime = "application/zip", fg = "#eb6f92" },
  { mime = "application/gzip", fg = "#eb6f92" },
  { mime = "application/x-tar", fg = "#eb6f92" },
  { mime = "application/x-bzip", fg = "#eb6f92" },
  { mime = "application/x-bzip2", fg = "#eb6f92" },
  { mime = "application/x-7z-compressed", fg = "#eb6f92" },
  { mime = "application/x-rar", fg = "#eb6f92" },

  # Empty files
  { mime = "inode/x-empty", fg = "#524f67" },

  # Fallback
  { name = "*", fg = "#e0def4" },
  { name = "*/", fg = "#e0def4" },
]
