return {
  {
    'nvim-treesitter/nvim-treesitter-textobjects',
    dependencies = { 'nvim-treesitter/nvim-treesitter' },
    lazy = true,
  },
  {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    config = function()
      require('nvim-treesitter.configs').setup({
        ensure_installed = {
          'bash',
          'c',
          'comment',
          'css',
          'csv',
          'diff',
          'dockerfile',
          'git_config',
          'git_rebase',
          'gitattributes',
          'gitcommit',
          'gitignore',
          'go',
          'gomod',
          'gosum',
          'gotmpl',
          'gowork',
          'gpg',
          'groovy',
          'hcl',
          'helm',
          'html',
          'html',
          'http',
          'ini',
          'jq',
          'jsdoc',
          'json',
          'json5',
          'jsonc',
          'jsonnet',
          'lua',
          'luadoc',
          'make',
          'markdown',
          'markdown_inline',
          'mermaid',
          'passwd',
          'python',
          'query',
          'regex',
          'requirements',
          'sql',
          'ssh_config',
          'terraform',
          'toml',
          'vim',
          'vimdoc',
          'yaml',
        },
        auto_installed = false,
        highlight = {
          enable = true,
          additional_vim_regex_highlighting = false,
        },
        indent = { enable = true },
        textobjects = {
          select = {
            enable = true,
            lookahead = true,
            keymaps = {
              ['af'] = '@function.outer',
              ['if'] = '@function.inner',
              ['ab'] = '@block.outer',
              ['ib'] = '@block.inner',
            },
            include_surrounding_whitespace = true,
          },
        },
      })
    end,
  },
}
