return {
  {
    'nvim-treesitter/nvim-treesitter',
    lazy = false,
    branch = 'main',
    build = ':TSUpdate',
    config = function()
      require('nvim-treesitter').install({
        ensure_installed = {
          'bash',
          'comment',
          'css',
          'csv',
          'diff',
          'dockerfile',
          'editorconfig',
          'fish',
          'git_config',
          'git_rebase',
          'gitcommit',
          'gitignore',
          'go',
          'gomod',
          'gosum',
          'gotmpl',
          'gowork',
          'groovy',
          'hcl',
          'helm',
          'html',
          'ini',
          'jsdoc',
          'json',
          'make',
          'regex',
          'requirements',
          'sql',
          'terraform',
          'toml',
          'yaml',
        },
      })
    end,
  },
}
