return {
  ensure_installed = {
    "actionlint",
    "ansible-language-server",
    "autopep8",
    "bash-language-server",
    "css-lsp",
    "docker-compose-language-service",
    "dockerfile-language-server",
    "hadolint",
    "helm-ls",
    "html-lsp",
    "json-lsp",
    "lua-language-server",
    "prettierd",
    "pylint",
    "python-lsp-server",
    "reorder-python-imports",
    "shellcheck",
    "sqlfmt",
    "sqlls",
    "stylelint",
    "stylua",
    "terraform-ls",
    "tflint",
    "yaml-language-server",
  },
}
