theme = "rose_pine"

[editor]
bufferline = "always"
color-modes = true
completion-trigger-len = 1
idle-timeout = 0
line-number = "relative"
middle-click-paste = false

[editor.statusline]
left = ["mode", "spinner", "file-base-name", "read-only-indicator", "file-modification-indicator", "version-control"]
right = ["register", "diagnostics", "position", "file-type", "file-encoding", "file-line-ending"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true
character = "┊"

[editor.gutters]
layout = ["diagnostics", "diff", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 1
