[[language]]
name = "groovy"
language-id = "groovy"
scope = "source.groovy"
file-types = ["groovy", "Jenkinsfile", "jenkinsfile"]
shebangs = ["groovy"]
roots = []
comment-token = "//"
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "groovy"
source = { git = "https://github.com/Decodetalkers/tree-sitter-groovy", rev = "gh-pages" }
